apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: quiz-app
  labels:
    role: api
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      containers:
        - name: api
          image: 023703779855.dkr.ecr.ap-south-1.amazonaws.com/dev/backend:8
          imagePullPolicy: IfNotPresent 
          envFrom:
            - configMapRef:
                name: mysql-config
            - secretRef:
                name: mysql-secret
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1

        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.33.0
          command:
            - "/cloud_sql_proxy"
            - "-instances=heroic-gamma-465105-c8:us-central1:quizdb=tcp:3306"
            - "-credential_file=/secrets/cloudsql/credentials.json"
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true

      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
