apiVersion: v1
kind: Service
metadata:
  namespace: quiz-app
  name: mongodb-svc
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
  clusterIP: None
