apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: quiz-app
spec:
  selector:
    role: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Or use NodePort if on local cluster
