name: Frontend GCP CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontendci.yaml'

env:
  BUILD_TAG: ${{ github.run_number }}
  GCP_REGION: us-central1
  GAR_REPO: microservicequiz
  GCP_PROJECT_ID: heroic-gamma-465105-c8

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Set up Docker auth for GAR
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > $HOME/gcp-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
          gcloud config set project ${{ env.GCP_PROJECT_ID }}
          gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev --quiet

      - name: 3. Build Docker Image
        working-directory: frontend
        run: |
          docker build -t frontend .

      - name: 4. Tag & Push to Artifact Registry (GAR)
        run: |
          GAR_IMAGE=${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPO }}/frontend:${{ env.BUILD_TAG }}
          docker tag frontend $GAR_IMAGE
          docker push $GAR_IMAGE
          echo "GAR_IMAGE=$GAR_IMAGE" >> $GITHUB_ENV

      - name: 5. Update Frontend Deployment YAML
        run: |
          sed -i "s|image: .*|image: ${{ env.GAR_IMAGE }}|" kubernetes/frontend/deployment.yaml

      - name: 6. Commit and Push Updated YAML
        run: |
          git config --global user.email "mspr9773@gmail.com"
          git config --global user.name "M Surya Prasad"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}

          git add kubernetes/frontend/deployment.yaml
          git diff --cached --quiet && echo "🟡 No changes to commit" || git commit -m "Update frontend image to ${{ env.BUILD_TAG }}"
          git push
